// Validates and merges the per-group raw question files into src/data/questions.ts.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const rawDir = join(root, 'src', 'data', 'raw')

const SPECS = new Set([
  'CEDS', 'SIF', 'Ed-Fi', 'PESC', 'CTDL', 'CLR', 'OpenBadges', 'Ed-API',
  'CASE', 'LIF', 'JEDx', 'SOC', 'CIP', 'SEDM', 'DCTAP', 'MedBiquitous',
  'SkillsProf',
])
const LAYERS = new Set(['data-model', 'transport', 'api'])
const DIFFS = new Set(['intro', 'core', 'advanced'])

const files = readdirSync(rawDir).filter((f) => f.endsWith('.json')).sort()
const all = []
const seenIds = new Set()
const issues = []

for (const file of files) {
  let arr
  try {
    arr = JSON.parse(readFileSync(join(rawDir, file), 'utf8'))
  } catch (e) {
    issues.push(`${file}: INVALID JSON — ${e.message}`)
    continue
  }
  if (!Array.isArray(arr)) { issues.push(`${file}: not an array`); continue }
  let kept = 0
  for (const q of arr) {
    const where = `${file}#${q && q.id}`
    if (!q || typeof q !== 'object') { issues.push(`${where}: not an object`); continue }
    if (!SPECS.has(q.spec)) { issues.push(`${where}: bad spec "${q.spec}"`); continue }
    if (!LAYERS.has(q.layer)) { issues.push(`${where}: bad layer "${q.layer}"`); continue }
    if (!Array.isArray(q.options) || q.options.length !== 4) { issues.push(`${where}: needs exactly 4 options`); continue }
    if (typeof q.answerIndex !== 'number' || q.answerIndex < 0 || q.answerIndex > 3) { issues.push(`${where}: bad answerIndex`); continue }
    if (!q.question || !q.explanation) { issues.push(`${where}: missing question/explanation`); continue }
    let id = String(q.id || `${q.spec}-${q.layer}-${kept}`)
    while (seenIds.has(id)) id = id + '_b'
    seenIds.add(id)
    if (!DIFFS.has(q.difficulty)) q.difficulty = 'core'
    all.push({
      id,
      spec: q.spec,
      layer: q.layer,
      difficulty: q.difficulty,
      concept: q.concept || 'General',
      question: q.question,
      options: q.options.map(String),
      answerIndex: q.answerIndex,
      explanation: q.explanation,
      source: q.source || '',
    })
    kept++
  }
  console.log(`${file}: ${kept}/${arr.length} kept`)
}

// Report distribution
const dist = {}
for (const q of all) {
  dist[q.spec] = dist[q.spec] || { 'data-model': 0, transport: 0, api: 0 }
  dist[q.spec][q.layer]++
}
console.log('\nDistribution by spec × layer:')
for (const s of SPECS) {
  const d = dist[s] || { 'data-model': 0, transport: 0, api: 0 }
  console.log(`  ${s.padEnd(13)} dm:${d['data-model']}  transport:${d.transport}  api:${d.api}`)
}
console.log(`\nTOTAL: ${all.length} questions`)
if (issues.length) {
  console.log(`\n⚠️  ${issues.length} issues:`)
  issues.forEach((i) => console.log('  - ' + i))
}

const header = `// AUTO-GENERATED by scripts/assemble.mjs from src/data/raw/*.json
// ${all.length} questions mined from the EDUcore knowledge graph. Do not edit by hand.
import type { Question } from '../lib/types'

export const QUESTIONS: Question[] = `
writeFileSync(join(root, 'src', 'data', 'questions.ts'), header + JSON.stringify(all, null, 2) + '\n')
console.log('\nWrote src/data/questions.ts')
